#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("disneyapp.Resource", IsApplication=true)]

namespace disneyapp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050017
			public const int activityviews = 2131034135;
			
			// aapt resource value: 0x7f05000a
			public const int awtlabel = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int description = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int descriptionlabel = 2131034116;
			
			// aapt resource value: 0x7f05001c
			public const int diningcosttype = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int diningcosttypelabel = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int diningcuisine = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int diningcuisinelabel = 2131034141;
			
			// aapt resource value: 0x7f050022
			public const int diningentreeprice = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int diningentreepricelabel = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int diningphone = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int diningphonelabel = 2131034143;
			
			// aapt resource value: 0x7f050024
			public const int diningspecialties = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int diningspecialtieslabel = 2131034147;
			
			// aapt resource value: 0x7f05001a
			public const int diningtype = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int diningtypelabel = 2131034137;
			
			// aapt resource value: 0x7f050009
			public const int duration = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int durationlabel = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int golabel = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int hotelAddress1 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int hotelAddress2 = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int hotelAddresslabel = 2131034125;
			
			// aapt resource value: 0x7f050016
			public const int hotelcategory = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int hotelcategorylabel = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int hotelcost = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int hotelcostlabel = 2131034131;
			
			// aapt resource value: 0x7f050010
			public const int hotelphone = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int hoteltheme = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int hotelthemelabel = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int opened = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int openedlabel = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int parkname = 2131034124;
			
			// aapt resource value: 0x7f050018
			public const int rowTextView = 2131034136;
			
			// aapt resource value: 0x7f050001
			public const int scope = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int scopelabel = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int waittime = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int whentogo = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int attractiondetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int attractionsactivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hoteldetail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int mainrow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int parksactivity = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int parksrow = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int restaurantdetail = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
